[package]
name = "acct_registry"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Brandon Arbuthnot (brandon@imbibed.life)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
suins = { git = "https://github.com/MystenLabs/suins-contracts.git", subdir = "packages/suins", rev = "4ec58e8155c0f8c1e6cd63df88d18cdf7b09bc62" }

[addresses]
acct_registry = "0x0"
sui = "0x2"

# Module structure:
# - registry.move: Main registry contract with namespace management
# - Tests will be in tests/ directory
